Hermoza.BibloMax.Integracion/Controllers/ComplejoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Hermoza.BibloMax.Servicios.Auth.Servicios.Abstracciones;
using Hermoza.BibloMax.Servicios.Complejos.Dtos;
using Hermoza.BibloMax.Servicios.Complejos.Servicios.Abstracciones;
using Hermoza.BibloMax.Servicios.General.Dtos;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Hermoza.BibloMax.Integracion.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class ComplejoController : ControllerBase
    {

        private readonly IComplejoServicio _complejoServicio;
        private readonly IAuthServicio _authServicio;

        public ComplejoController(IComplejoServicio complejoServicio,
                              IAuthServicio authServicio)
        {
            _complejoServicio = complejoServicio;
            _authServicio = authServicio;
        }



        [HttpPost]
        [Route("RegistrarComplejo")]
        public async Task<OperacionDto<OperacionComplejoRespuestaDto>> RegistrarComplejo(RegistrarComplejoPeticionDto peticion)
        {

            if (!string.IsNullOrEmpty(peticion.Id))
            {
                var editar = await _complejoServicio.EditarComplejo(peticion);
                return editar;
            }

            var registrar = await _complejoServicio.RegistrarComplejo(peticion);

            return registrar;

        }

        [HttpPost]
        [Route("ObtenerComplejos")]
        public async Task<ObtenerComplejosDto> ObtenerComplejos()
        {

            var operacion = await _complejoServicio.ObtenerComplejos();

            return operacion.Resultado;

        }

        [HttpPost]
        [Route("DetalleComplejo")]
        public async Task<OperacionDto<RegistrarComplejoPeticionDto>> DetalleComplejo(PeticionIdDto peticion)
        {

            var id = String.IsNullOrEmpty(peticion.Id) ? "" : peticion.Id;

            var operacion = await _complejoServicio.DetalleComplejo(id);

            return operacion;

        }

        [HttpPost]
        [Route("EliminarComplejo")]
        public async Task<OperacionDto<OperacionComplejoRespuestaDto>> EliminarComplejo(PeticionIdDto peticion)
        {

            var id = String.IsNullOrEmpty(peticion.Id) ? "" : peticion.Id;

            var operacion = await _complejoServicio.EliminarComplejo(id);

            return operacion;

        }

        [HttpPost]
        [Route("EditarComplejo")]
        public async Task<OperacionDto<OperacionComplejoRespuestaDto>> EditarComplejo(RegistrarComplejoPeticionDto peticion)
        {

            var operacion = await _complejoServicio.EditarComplejo(peticion);

            return operacion;

        }

    }
}

Hermoza.BibloMax.Integracion/Controllers/SedeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Hermoza.BibloMax.Integracion.Infraestructura.Seguridad;
using Hermoza.BibloMax.Servicios.Auth.Servicios.Abstracciones;
using Hermoza.BibloMax.Servicios.General.Dtos;
using Hermoza.BibloMax.Servicios.Sedes.Dtos;
using Hermoza.BibloMax.Servicios.Sedes.Servicios.Abstracciones;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Hermoza.BibloMax.Integracion.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class SedeController : ControladorBase
    {

        private readonly ISedeServicio _sedeServicio;
        private readonly IAuthServicio _authServicio;

        public SedeController(ISedeServicio sedeServicio,
                              IAuthServicio authServicio)
        {
            _sedeServicio = sedeServicio;
            _authServicio = authServicio;
        }



        [HttpPost]
        [Route("RegistrarSede")]
        public async Task<OperacionDto<OperacionSedeRespuestaDto>> RegistrarSede(RegistrarSedePeticionDto peticion)
        {

            if (!string.IsNullOrEmpty(peticion.Id))
            {
                var editar = await _sedeServicio.EditarSede(peticion);
                return editar;
            }

            var registrar = await _sedeServicio.RegistrarSede(peticion);

            return registrar;

        }

        [HttpPost]
        [Route("ObtenerSedes")]
        public async Task<ObtenerSedesDto> ObtenerSedes()
        {

            var operacion = await _sedeServicio.ObtenerSedes();

            return operacion.Resultado;

        }

        [HttpPost]
        [Route("DetalleSede")]
        public async Task<OperacionDto<RegistrarSedePeticionDto>> DetalleSede(PeticionIdDto peticion)
        {

            var id = String.IsNullOrEmpty(peticion.Id) ? "" : peticion.Id;

            var operacion = await _sedeServicio.DetalleSede(id);

            return operacion;

        }

        [HttpPost]
        [Route("EliminarSede")]
        public async Task<OperacionDto<OperacionSedeRespuestaDto>> EliminarSede(PeticionIdDto peticion)
        {

            var id = String.IsNullOrEmpty(peticion.Id) ? "" : peticion.Id;

            var operacion = await _sedeServicio.EliminarSede(id);

            return operacion;

        }

        [HttpPost]
        [Route("EditarSede")]
        public async Task<OperacionDto<OperacionSedeRespuestaDto>> EditarSede(RegistrarSedePeticionDto peticion)
        {

            var operacion = await _sedeServicio.EditarSede(peticion);

            return operacion;

        }

    }
}

Hermoza.BibloMax.Integracion/Pages/Complejos/SOComplejos.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Hermoza.BibloMax.Integracion.Pages.Complejos
{
    public class SOComplejosModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Hermoza.BibloMax.Integracion/Pages/Complejos/SOComplejos.cshtml
@page
@model Hermoza.BibloMax.Integracion.Pages.Complejos.SOComplejosModel
@{
    Layout = "_Layout";
}

<input type="hidden" id="__URL_SEDES" value="@Url.Action("ObtenerSedes","Sede")" />
<input type="hidden" id="__URL_COMPLEJOS" value="@Url.Action("ObtenerComplejos","Complejo")" />
<input type="hidden" id="__URL_DETALLE" value="@Url.Action("DetalleComplejo","Complejo")" />
<input type="hidden" id="__URL_ELIMINAR" value="@Url.Action("EliminarComplejo","Complejo")" />
<input type="hidden" id="__URL_REGISTRO" value="@Url.Action("RegistrarComplejo","Complejo")" />
<input type="hidden" id="__ID_ACTUAL" />

@section PageHeader{
    <header class="masthead mb-auto">
        <div class="inner">
            <h3 class="masthead-brand">BibloMax</h3>
            <nav class="nav nav-masthead justify-content-center">
                <a class="nav-link" href="@Url.Page("/Principal/SOIndex")">Inicio</a>
                <a class="nav-link" href="@Url.Page("/Sedes/SOSedes")">Sedes</a>
                <a class="nav-link active" href="@Url.Page("/Complejos/SOComplejos")">Complejos</a>
                <a class="nav-link" href="@Url.Page("/Principal/SONosotros")">Nosotros</a>
            </nav>
        </div>
    </header>
}

<main role="main" class="inner cover">

    <div class="d-flex flex-wrap bg-light text-dark text-left" style="margin-bottom:5%; padding:15px;">

        <div class="form-group col-12">
            <h3>Complejos</h3>
        </div>

        <div class="form-group col-lg-6 col-sm-12">
            <label for="pwd">Sede:</label>
            @*<input type="number" class="form-control" id="txtSede" placeholder="Sede">*@
            <select class="form-control" id="cboSede">
                <option value="0">Seleccione</option>
            </select>
        </div>

        <div class="form-group col-lg-6 col-sm-12">
            <label for="email">Localidad:</label>
            <input type="text" class="form-control" id="txtLocalidad" placeholder="Localidad">
        </div>

        <div class="form-group col-lg-6 col-sm-12">
            <label for="pwd">Jefe:</label>
            <input type="text" class="form-control" id="txtJefe" placeholder="Jefe">
        </div>

        <div class="form-group col-lg-6 col-sm-12">
            <label for="email">N° Areas:</label>
            <input type="number" class="form-control" id="txtAreas" placeholder="N° Areas">
        </div>

        <div class="d-flex flex-wrap flex-row-reverse col-12">
            <button type="button" class="m-1 col-lg-3 col-12 btn btn-dark btn-block" id="btnGuardar">Guardar</button>
            <button type="button" class="m-1 col-lg-3 col-12 btn btn-dark btn-block" id="btnLimpiar">Limpiar</button>
        </div>
    </div>

    <table id="example" class="display" style="width:100%">
        <thead class="bg-dark">
            <tr>
                <th scope="col">Sede</th>
                <th scope="col">Localidad</th>
                <th scope="col">Jefe</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody style="background-color: rgba(0,0,0,0.3);" class="text-dark">
        </tbody>
    </table>

</main>

@section Javascript{
    <script src="~/js/complejos/complejos.js"></script>
}